// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcPErs1b66rESk2lG_WHv1nBMRNTaNXBc',
    appId: '1:778581707854:web:0f36688886f2586a05871f',
    messagingSenderId: '778581707854',
    projectId: 'onlinevotingapp-e375b',
    authDomain: 'onlinevotingapp-e375b.firebaseapp.com',
    storageBucket: 'onlinevotingapp-e375b.firebasestorage.app',
    measurementId: 'G-F0SX1G38HP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBczD4uM2Koi7WPEpf7rD7qmDVLP8iEm0s',
    appId: '1:778581707854:android:8e5cdd0fc951fb9705871f',
    messagingSenderId: '778581707854',
    projectId: 'onlinevotingapp-e375b',
    storageBucket: 'onlinevotingapp-e375b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXPOkcNAge82Z4RplcIyc0PA71tk1zZ3E',
    appId: '1:778581707854:ios:2b1609eb7eaa1fbe05871f',
    messagingSenderId: '778581707854',
    projectId: 'onlinevotingapp-e375b',
    storageBucket: 'onlinevotingapp-e375b.firebasestorage.app',
    iosBundleId: 'com.meta.mayapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXPOkcNAge82Z4RplcIyc0PA71tk1zZ3E',
    appId: '1:778581707854:ios:2b1609eb7eaa1fbe05871f',
    messagingSenderId: '778581707854',
    projectId: 'onlinevotingapp-e375b',
    storageBucket: 'onlinevotingapp-e375b.firebasestorage.app',
    iosBundleId: 'com.meta.mayapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcPErs1b66rESk2lG_WHv1nBMRNTaNXBc',
    appId: '1:778581707854:web:11a3d72f4b75613105871f',
    messagingSenderId: '778581707854',
    projectId: 'onlinevotingapp-e375b',
    authDomain: 'onlinevotingapp-e375b.firebaseapp.com',
    storageBucket: 'onlinevotingapp-e375b.firebasestorage.app',
    measurementId: 'G-6NT3QHEP1L',
  );
}
